const milestoneImages = [
  {
    id: 1,
    imgPath: require("../../assets/img/Milestones/2MONTHS/SOCIAL/2MONTHS_SOCIAL_1.png"),
    behaviour: "Begins to smile at people",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 2,
    imgPath: require("../../assets/img/Milestones/2MONTHS/SOCIAL/2MONTHS_SOCIAL_2.png"),
    behaviour:
      "Can briefly calm himself (may bring hands to mouth and suck on hand)",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 3,
    imgPath: require("../../assets/img/Milestones/2MONTHS/SOCIAL/2MONTHS_SOCIAL_3.png"),
    behaviour: "Tries to look at parent",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 4,
    imgPath: require("../../assets/img/Milestones/2MONTHS/COMMUNICATION/2MONTHS_COMMUNICATION_1.png"),
    behaviour: "Coos, makes gurgling sounds",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 5,
    imgPath: require("../../assets/img/Milestones/2MONTHS/COMMUNICATION/2MONTHS_COMMUNICATION_2.png"),
    behaviour: "Turns head toward sounds",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 6,
    imgPath: require("../../assets/img/Milestones/2MONTHS/COGNITIVE/2MONTHS_COGNITIVE_1.png"),
    behaviour: "Pays attention to faces",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 7,
    imgPath: require("../../assets/img/Milestones/2MONTHS/COGNITIVE/2MONTHS_COGNITIVE_2.png"),
    behaviour:
      "Begins to follow things with eyes and recognize people at a distance",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 8,
    imgPath: require("../../assets/img/Milestones/2MONTHS/COGNITIVE/2MONTHS_COGNITIVE_3.png"),
    behaviour: "Begins to act bored (cries, fussy) if activity doesn’t change",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 9,
    imgPath: require("../../assets/img/Milestones/2MONTHS/PHYSICAL_DEVELOPMENT/2MONTHS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Can hold head up and begins to push up when lying on tummy",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 10,
    imgPath: require("../../assets/img/Milestones/2MONTHS/PHYSICAL_DEVELOPMENT/2MONTHS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Makes smoother movements with arms and legs",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 11,
    imgPath: "",
    behaviour: "Doesn’t respond to loud sounds",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 12,
    imgPath: "",
    behaviour: "Doesn’t watch things as they move",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 13,
    imgPath: "",
    behaviour: "Doesn’t smile at people",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 14,
    imgPath: "",
    behaviour: "Doesn’t bring hands to mouth",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 15,
    imgPath: "",
    behaviour: "Can’t hold head up when pushing up when on tummy",
    description: "",
    atAge: 2,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 16,
    imgPath: require("../../assets/img/Milestones/4MONTHS/SOCIAL/4MONTHS_SOCIAL_1.png"),
    behaviour: "Smiles spontaneously, especially at people",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 17,
    imgPath: require("../../assets/img/Milestones/4MONTHS/SOCIAL/4MONTHS_SOCIAL_2.png"),
    behaviour: "Likes to play with people and might cry when playing stops",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 18,
    imgPath: require("../../assets/img/Milestones/4MONTHS/SOCIAL/4MONTHS_SOCIAL_3.png"),
    behaviour:
      "Copies some movements and facial expressions, like smiling or frowning",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 19,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COMMUNICATION/4MONTHS_COMMUNICATION_1.png"),
    behaviour: "Begins to babble",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 20,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COMMUNICATION/4MONTHS_COMMUNICATION_2.png"),
    behaviour: "Babbles with expression and copies sounds he hears",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 21,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COMMUNICATION/4MONTHS_COMMUNICATION_3.png"),
    behaviour: "Cries in different ways to show hunger, pain, or being tired",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 22,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_1.png"),
    behaviour: "Lets you know if she is happy or sad",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 23,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_2.png"),
    behaviour: "Responds to affection",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 24,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_3.png"),
    behaviour: "Reaches for toy with one hand",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 25,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_4.png"),
    behaviour:
      "Uses hands and eyes together, such as seeing a toy and reaching for it",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 26,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_5.png"),
    behaviour: "Follows moving things with eyes from side to side",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 27,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_6.png"),
    behaviour: "Watches faces closely",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 28,
    imgPath: require("../../assets/img/Milestones/4MONTHS/COGNITIVE/4MONTHS_COGNITIVE_7.png"),
    behaviour: "Recognizes familiar people and things at a distance",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 29,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Holds head steady, unsupported",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 30,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Pushes down on legs when feet are on a hard surface",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 31,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "May be able to roll over from tummy to back",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 32,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Can hold a toy and shake it and swing at dangling toys",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 33,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_5.png"),
    behaviour: "Brings hands to mouth",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 34,
    imgPath: require("../../assets/img/Milestones/4MONTHS/PHYSICAL_DEVELOPMENT/4MONTHS_PHYSICAL_DEVELOPMENT_6.png"),
    behaviour: "When lying on stomach, pushes up to elbows",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 35,
    imgPath: "",
    behaviour: "Doesn’t watch things as they move",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 36,
    imgPath: "",
    behaviour: "Doesn’t smile at people",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 37,
    imgPath: "",
    behaviour: "Can’t hold head steady",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 38,
    imgPath: "",
    behaviour: "Doesn’t coo or make sounds",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 39,
    imgPath: "",
    behaviour: "Doesn’t bring things to mouth",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 40,
    imgPath: "",
    behaviour:
      "Doesn’t push down with legs when feet are placed on a hard surface",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 41,
    imgPath: "",
    behaviour: "Has trouble moving one or both eyes in all directions",
    description: "",
    atAge: 4,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 42,
    imgPath: require("../../assets/img/Milestones/6MONTHS/SOCIAL/6MONTHS_SOCIAL_1.png"),
    behaviour:
      "Knows familiar faces and begins to know if someone is a stranger",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 43,
    imgPath: require("../../assets/img/Milestones/6MONTHS/SOCIAL/6MONTHS_SOCIAL_2.png"),
    behaviour: "Likes to play with others, especially parents",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 44,
    imgPath: require("../../assets/img/Milestones/6MONTHS/SOCIAL/6MONTHS_SOCIAL_3.png"),
    behaviour: "Responds to other people’s emotions and often seems happy",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 45,
    imgPath: require("../../assets/img/Milestones/6MONTHS/SOCIAL/6MONTHS_SOCIAL_4.png"),
    behaviour: "Likes to look at self in a mirror",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 46,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COMMUNICATION/6MONTHS_COMMUNICATION_1.png"),
    behaviour: "Responds to sounds by making sounds",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 47,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COMMUNICATION/6MONTHS_COMMUNICATION_2.png"),
    behaviour:
      "Strings vowels together when babbling (“ah,” “eh,” “oh”) and likes taking turns with parent while making sounds",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 48,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COMMUNICATION/6MONTHS_COMMUNICATION_3.png"),
    behaviour: "Responds to own name",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 49,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COMMUNICATION/6MONTHS_COMMUNICATION_4.png"),
    behaviour: "Makes sounds to show joy and displeasure",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 50,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COMMUNICATION/6MONTHS_COMMUNICATION_5.png"),
    behaviour: "Begins to say consonant sounds (jabbering with “m,” “b”)",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 51,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COGNITIVE/6MONTHS_COGNITIVE_1.png"),
    behaviour: "Looks around at things nearby",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 52,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COGNITIVE/6MONTHS_COGNITIVE_2.png"),
    behaviour: "Brings things to mouth",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 53,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COGNITIVE/6MONTHS_COGNITIVE_3.png"),
    behaviour:
      "Shows curiosity about things and tries to get things that are out of reach",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 54,
    imgPath: require("../../assets/img/Milestones/6MONTHS/COGNITIVE/6MONTHS_COGNITIVE_4.png"),
    behaviour: "Begins to pass things from one hand to the other",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 55,
    imgPath: require("../../assets/img/Milestones/6MONTHS/PHYSICAL_DEVELOPMENT/6MONTHS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Rolls over in both directions (front to back, back to front)",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 56,
    imgPath: require("../../assets/img/Milestones/6MONTHS/PHYSICAL_DEVELOPMENT/6MONTHS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Begins to sit without support",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 57,
    imgPath: require("../../assets/img/Milestones/6MONTHS/PHYSICAL_DEVELOPMENT/6MONTHS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "When standing, supports weight on legs and might bounce",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 58,
    imgPath: require("../../assets/img/Milestones/6MONTHS/PHYSICAL_DEVELOPMENT/6MONTHS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour:
      "Rocks back and forth, sometimes crawling backward before moving forward",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 59,
    imgPath: "",
    behaviour: "Doesn’t try to get things that are in reach",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 60,
    imgPath: "",
    behaviour: "Shows no affection for caregivers",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 61,
    imgPath: "",
    behaviour: "Doesn’t respond to sounds around him",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 62,
    imgPath: "",
    behaviour: "Has difficulty getting things to mouth",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 63,
    imgPath: "",
    behaviour: "Doesn’t make vowel sounds (“ah”, “eh”, “oh”)",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 64,
    imgPath: "",
    behaviour: "Doesn’t roll over in either direction",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 65,
    imgPath: "",
    behaviour: "Doesn’t laugh or make squealing sounds",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 66,
    imgPath: "",
    behaviour: "Seems very stiff, with tight muscles",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 67,
    imgPath: "",
    behaviour: "Seems very floppy, like a rag doll",
    description: "",
    atAge: 6,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 68,
    imgPath: require("../../assets/img/Milestones/9MONTHS/SOCIAL/9MONTHS_SOCIAL_1.png"),
    behaviour: "May be afraid of strangers",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 69,
    imgPath: require("../../assets/img/Milestones/9MONTHS/SOCIAL/9MONTHS_SOCIAL_2.png"),
    behaviour: "May be clingy with familiar adults",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 70,
    imgPath: require("../../assets/img/Milestones/9MONTHS/SOCIAL/9MONTHS_SOCIAL_3.png"),
    behaviour: "Has favorite toys",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 71,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COMMUNICATION/9MONTHS_COMMUNICATION_1.png"),
    behaviour: "Understands “no”",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 72,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COMMUNICATION/9MONTHS_COMMUNICATION_2.png"),
    behaviour:
      "Makes a lot of different sounds like “mamamama” and “bababababa”",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 73,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COMMUNICATION/9MONTHS_COMMUNICATION_3.png"),
    behaviour: "Copies sounds and gestures of others",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 74,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COMMUNICATION/9MONTHS_COMMUNICATION_4.png"),
    behaviour: "Uses fingers to point at things",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 75,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_1.png"),
    behaviour: "Watches the path of something as it falls",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 76,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_2.png"),
    behaviour: "Looks for things he sees you hide",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 77,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_3.png"),
    behaviour: "Plays peek-a-boo",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 78,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_4.png"),
    behaviour: "Puts things in her mouth",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 79,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_5.png"),
    behaviour: "Moves things smoothly from one hand to the other",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 80,
    imgPath: require("../../assets/img/Milestones/9MONTHS/COGNITIVE/9MONTHS_COGNITIVE_6.png"),
    behaviour: "Picks up things like cereal o’s between thumb and index finger",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 81,
    imgPath: require("../../assets/img/Milestones/9MONTHS/PHYSICAL_DEVELOPMENT/9MONTHS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Stands, holding on",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 82,
    imgPath: require("../../assets/img/Milestones/9MONTHS/PHYSICAL_DEVELOPMENT/9MONTHS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Can get into sitting position",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 83,
    imgPath: require("../../assets/img/Milestones/9MONTHS/PHYSICAL_DEVELOPMENT/9MONTHS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Sits without support",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 84,
    imgPath: require("../../assets/img/Milestones/9MONTHS/PHYSICAL_DEVELOPMENT/9MONTHS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Pulls to stand",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 85,
    imgPath: require("../../assets/img/Milestones/9MONTHS/PHYSICAL_DEVELOPMENT/9MONTHS_PHYSICAL_DEVELOPMENT_5.png"),
    behaviour: "Crawls",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 86,
    imgPath: "",
    behaviour: "Doesn’t bear weight on legs with support",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 87,
    imgPath: "",
    behaviour: "Doesn’t sit with help",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 88,
    imgPath: "",
    behaviour: "Doesn’t babble (“mama”, “baba”, “dada”)",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 89,
    imgPath: "",
    behaviour: "Doesn’t play any games involving back-and-forth play",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 90,
    imgPath: "",
    behaviour: "Doesn’t respond to own name",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 91,
    imgPath: "",
    behaviour: "Doesn’t seem to recognize familiar people",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 92,
    imgPath: "",
    behaviour: "Doesn’t look where you point",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 93,
    imgPath: "",
    behaviour: "Doesn’t transfer toys from one hand to the other",
    description: "",
    atAge: 9,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 94,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_1.png"),
    behaviour: "Is shy or nervous with strangers",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 95,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_2.png"),
    behaviour: "Cries when mom or dad leaves",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 96,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_3.png"),
    behaviour: "Has favorite things and people",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 97,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_4.png"),
    behaviour: "Shows fear in some situations",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 98,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_5.png"),
    behaviour: "Hands you a book when he wants to hear a story",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 99,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_6.png"),
    behaviour: "Repeats sounds or actions to get attention",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 100,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_7.png"),
    behaviour: "Puts out arm or leg to help with dressing",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 101,
    imgPath: require("../../assets/img/Milestones/1YEARS/SOCIAL/1YEARS_SOCIAL_8.png"),
    behaviour: "Plays games such as “peek-a-boo” and “pat-a-cake”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 102,
    imgPath: require("../../assets/img/Milestones/1YEARS/COMMUNICATION/1YEARS_COMMUNICATION_1.png"),
    behaviour: "Responds to simple spoken requests",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 103,
    imgPath: require("../../assets/img/Milestones/1YEARS/COMMUNICATION/1YEARS_COMMUNICATION_2.png"),
    behaviour:
      "Uses simple gestures, like shaking head “no” or waving “bye-bye”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 104,
    imgPath: require("../../assets/img/Milestones/1YEARS/COMMUNICATION/1YEARS_COMMUNICATION_3.png"),
    behaviour: "Makes sounds with changes in tone (sounds more like speech) ”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 105,
    imgPath: require("../../assets/img/Milestones/1YEARS/COMMUNICATION/1YEARS_COMMUNICATION_4.png"),
    behaviour: "Says “mama” and “dada” and exclamations like “uh-oh!”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 106,
    imgPath: require("../../assets/img/Milestones/1YEARS/COMMUNICATION/1YEARS_COMMUNICATION_5.png"),
    behaviour: "Tries to say words you say",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 107,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_1.png"),
    behaviour:
      "Explores things in different ways, like shaking, banging, throwing",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 108,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_2.png"),
    behaviour: "Finds hidden things easily",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 109,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_3.png"),
    behaviour: "Looks at the right picture or thing when it’s named",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 110,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_4.png"),
    behaviour: "Copies gestures",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 111,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_5.png"),
    behaviour:
      "Starts to use things correctly; for example, drinks from a cup, brushes hair",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 112,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_6.png"),
    behaviour: "Bangs two things together",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 113,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_7.png"),
    behaviour: "Puts things in a container, takes things out of a container",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 114,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_8.png"),
    behaviour: "Lets things go without help",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 115,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_9.png"),
    behaviour: "Pokes with index (pointer) finger",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 116,
    imgPath: require("../../assets/img/Milestones/1YEARS/COGNITIVE/1YEARS_COGNITIVE_10.png"),
    behaviour: "Follows simple directions like “pick up the toy”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 117,
    imgPath: require("../../assets/img/Milestones/1YEARS/PHYSICAL_DEVELOPMENT/1YEARS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Gets to a sitting position without help",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 118,
    imgPath: require("../../assets/img/Milestones/1YEARS/PHYSICAL_DEVELOPMENT/1YEARS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Pulls up to stand, walks holding on to furniture (“cruising”)",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 119,
    imgPath: require("../../assets/img/Milestones/1YEARS/PHYSICAL_DEVELOPMENT/1YEARS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "May take a few steps without holding on",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 120,
    imgPath: require("../../assets/img/Milestones/1YEARS/PHYSICAL_DEVELOPMENT/1YEARS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "May stand alone",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 121,
    imgPath: "",
    behaviour: "Doesn’t crawl",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 122,
    imgPath: "",
    behaviour: "Can’t stand when supported",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 123,
    imgPath: "",
    behaviour: "Doesn’t search for things that she sees you hide",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 124,
    imgPath: "",
    behaviour: "Doesn’t say single words like “mama” or “dada”",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 125,
    imgPath: "",
    behaviour: "Doesn’t learn gestures like waving or shaking head",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 126,
    imgPath: "",
    behaviour: "Doesn’t point to things",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 127,
    imgPath: "",
    behaviour: "Loses skills he once had",
    description: "",
    atAge: 1,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 128,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_1.png"),
    behaviour: "Likes to hand things to others as play",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 129,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_2.png"),
    behaviour: "May have temper tantrums",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 130,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_3.png"),
    behaviour: "May be afraid of strangers",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 131,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_4.png"),
    behaviour: "Shows affection to familiar people",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 132,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_5.png"),
    behaviour: "Plays simple pretend, such as feeding a doll",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 133,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_6.png"),
    behaviour: "May cling to caregivers in new situations",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 134,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_7.png"),
    behaviour: "Points to show others something interesting",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 135,
    imgPath: require("../../assets/img/Milestones/18MONTHS/SOCIAL/18MONTHS_SOCIAL_8.png"),
    behaviour: "Explores alone but with parent close by",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 136,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COMMUNICATION/18MONTHS_COMMUNICATION_1.png"),
    behaviour: "Says several single words",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 137,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COMMUNICATION/18MONTHS_COMMUNICATION_2.png"),
    behaviour: "Says and shakes head “no”",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 138,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COMMUNICATION/18MONTHS_COMMUNICATION_3.png"),
    behaviour: "Points to show someone what he wants",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 139,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_1.png"),
    behaviour:
      "Knows what ordinary things are for; for example, telephone, brush, spoon",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 140,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_2.png"),
    behaviour: "Points to get the attention of others",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 141,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_3.png"),
    behaviour:
      "Shows interest in a doll or stuffed animal by pretending to feed",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 142,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_4.png"),
    behaviour: "Points to one body part",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 143,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_5.png"),
    behaviour: "Scribbles on his own",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 144,
    imgPath: require("../../assets/img/Milestones/18MONTHS/COGNITIVE/18MONTHS_COGNITIVE_6.png"),
    behaviour:
      "Can follow 1-step verbal commands without any gestures; for example, sits when you say “sit down”",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 145,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Walks alone",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 146,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "May walk up steps and run",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 147,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Pulls toys while walking",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 148,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Can help undress herself",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 149,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_5.png"),
    behaviour: "Drinks from a cup",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 150,
    imgPath: require("../../assets/img/Milestones/18MONTHS/PHYSICAL_DEVELOPMENT/18MONTHS_PHYSICAL_DEVELOPMENT_6.png"),
    behaviour: "Eats with a spoon",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 151,
    imgPath: "",
    behaviour: "Doesn’t point to show things to others",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 152,
    imgPath: "",
    behaviour: "Can’t walk",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 153,
    imgPath: "",
    behaviour: "Doesn’t know what familiar things are for",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 154,
    imgPath: "",
    behaviour: "Doesn’t copy others",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 155,
    imgPath: "",
    behaviour: "Doesn’t gain new words",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 156,
    imgPath: "",
    behaviour: "Doesn’t have at least 6 words",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 157,
    imgPath: "",
    behaviour: "Doesn’t notice or mind when a caregiver leaves or returns",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 158,
    imgPath: "",
    behaviour: "Loses skills he once had",
    description: "",
    atAge: 18,
    atAgeUnit: "MONTHS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 159,
    imgPath: require("../../assets/img/Milestones/2YEARS/SOCIAL/2YEARS_SOCIAL_1.png"),
    behaviour: "Copies others, especially adults and older children",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 160,
    imgPath: require("../../assets/img/Milestones/2YEARS/SOCIAL/2YEARS_SOCIAL_2.png"),
    behaviour: "Gets excited when with other children",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 161,
    imgPath: require("../../assets/img/Milestones/2YEARS/SOCIAL/2YEARS_SOCIAL_3.png"),
    behaviour: "Shows more and more independence",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 162,
    imgPath: require("../../assets/img/Milestones/2YEARS/SOCIAL/2YEARS_SOCIAL_4.png"),
    behaviour: "Shows defiant behavior (doing what he has been told not to)",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 163,
    imgPath: require("../../assets/img/Milestones/2YEARS/SOCIAL/2YEARS_SOCIAL_5.png"),
    behaviour:
      "Plays mainly beside other children, but is beginning to include other children, such as in chase games",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 164,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_1.png"),
    behaviour: "Points to things or pictures when they are named",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 165,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_2.png"),
    behaviour: "Knows names of familiar people and body parts",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 166,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_3.png"),
    behaviour: "Says sentences with 2 to 4 words",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 167,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_4.png"),
    behaviour: "Follows simple instructions",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 168,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_5.png"),
    behaviour: "Repeats words overheard in conversation",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 169,
    imgPath: require("../../assets/img/Milestones/2YEARS/COMMUNICATION/2YEARS_COMMUNICATION_6.png"),
    behaviour: "Points to things in a book",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 170,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_1.png"),
    behaviour: "Finds things even when hidden under two or three covers",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 171,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_2.png"),
    behaviour: "Begins to sort shapes and colors",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 172,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_3.png"),
    behaviour: "Completes sentences and rhymes in familiar books",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 173,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_4.png"),
    behaviour: "Plays simple make-believe games",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 174,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_5.png"),
    behaviour: "Builds towers of 4 or more blocks",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 175,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_6.png"),
    behaviour: "Might use one hand more than the other",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 176,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_7.png"),
    behaviour:
      "Follows two-step instructions such as “Pick up your shoes and put them in the closet.”",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 177,
    imgPath: require("../../assets/img/Milestones/2YEARS/COGNITIVE/2YEARS_COGNITIVE_8.png"),
    behaviour: "Names items in a picture book such as a cat, bird, or dog",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 178,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Stands on tiptoe",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 179,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Kicks a ball",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 180,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Begins to run ",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 181,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Climbs onto and down from furniture without help",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 182,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_5.png"),
    behaviour: "Walks up and down stairs holding on",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 183,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_6.png"),
    behaviour: "Throws ball overhand",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 184,
    imgPath: require("../../assets/img/Milestones/2YEARS/PHYSICAL_DEVELOPMENT/2YEARS_PHYSICAL_DEVELOPMENT_7.png"),
    behaviour: "Makes or copies straight lines and circles",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 185,
    imgPath: "",
    behaviour: "Doesn’t use 2-word phrases (for example, “drink milk”)",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 186,
    imgPath: "",
    behaviour:
      "Doesn’t know what to do with common things, like a brush, phone, fork, spoon",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 187,
    imgPath: "",
    behaviour: "Doesn’t copy actions and words",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 188,
    imgPath: "",
    behaviour: "Doesn’t follow simple instructions",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 189,
    imgPath: "",
    behaviour: "Doesn’t walk steadily",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 190,
    imgPath: "",
    behaviour: "Loses skills she once had",
    description: "",
    atAge: 2,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 191,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_1.png"),
    behaviour: "Copies adults and friends",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 192,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_2.png"),
    behaviour: "Shows affection for friends without prompting",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 193,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_3.png"),
    behaviour: "Takes turns in games",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 194,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_4.png"),
    behaviour: "Shows concern for a crying friend",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 195,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_5.png"),
    behaviour: "Understands the idea of “mine” and “his” or “hers”",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 196,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_6.png"),
    behaviour: "Shows a wide range of emotions",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 197,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_7.png"),
    behaviour: "Separates easily from mom and dad",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 198,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_8.png"),
    behaviour: "May get upset with major changes in routine",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 199,
    imgPath: require("../../assets/img/Milestones/3YEARS/SOCIAL/3YEARS_SOCIAL_9.png"),
    behaviour: "Dresses and undresses self",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 200,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_1.png"),
    behaviour: "Follows instructions with 2 or 3 steps",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 201,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_2.png"),
    behaviour: "Can name most familiar things",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 202,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_3.png"),
    behaviour: "Understands words like “in,” “on,” and “under”",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 203,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_4.png"),
    behaviour: "Says first name, age, and sex",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 204,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_5.png"),
    behaviour: "Names a friend",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 205,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_6.png"),
    behaviour:
      "Says words like “I,” “me,” “we,” and “you” and some plurals (cars, dogs, cats)",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 206,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_7.png"),
    behaviour: "Talks well enough for strangers to understand most of the time",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 207,
    imgPath: require("../../assets/img/Milestones/3YEARS/COMMUNICATION/3YEARS_COMMUNICATION_8.png"),
    behaviour: "Carries on a conversation using 2 to 3 sentences",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 208,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_1.png"),
    behaviour: "Can work toys with buttons, levers, and moving parts",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 209,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_2.png"),
    behaviour: "Plays make-believe with dolls, animals, and people",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 210,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_3.png"),
    behaviour: "Does puzzles with 3 or 4 pieces",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 211,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_4.png"),
    behaviour: "Understands what “two” means",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 212,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_5.png"),
    behaviour: "Copies a circle with pencil or crayon",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 213,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_6.png"),
    behaviour: "Turns book pages one at a time",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 214,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_7.png"),
    behaviour: "Builds towers of more than 6 blocks",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 215,
    imgPath: require("../../assets/img/Milestones/3YEARS/COGNITIVE/3YEARS_COGNITIVE_8.png"),
    behaviour: "Screws and unscrews jar lids or turns door handle",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 216,
    imgPath: require("../../assets/img/Milestones/3YEARS/PHYSICAL_DEVELOPMENT/3YEARS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Climbs well",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 217,
    imgPath: require("../../assets/img/Milestones/3YEARS/PHYSICAL_DEVELOPMENT/3YEARS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Runs easily",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 218,
    imgPath: require("../../assets/img/Milestones/3YEARS/PHYSICAL_DEVELOPMENT/3YEARS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Pedals a tricycle (3-wheel bike)",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 219,
    imgPath: require("../../assets/img/Milestones/3YEARS/PHYSICAL_DEVELOPMENT/3YEARS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Walks up and down stairs, one foot on each step",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 220,
    imgPath: "",
    behaviour: "Falls down a lot or has trouble with stairs",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 221,
    imgPath: "",
    behaviour: "Drools or has very unclear speech",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 222,
    imgPath: "",
    behaviour:
      "Can’t work simple toys (such as peg boards, simple puzzles, turning handle)",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 223,
    imgPath: "",
    behaviour: "Doesn’t speak in sentences",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 224,
    imgPath: "",
    behaviour: "Doesn’t understand simple instructions",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 225,
    imgPath: "",
    behaviour: "Doesn’t play pretend or make-believe",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 226,
    imgPath: "",
    behaviour: "Doesn’t want to play with other children or with toys",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 227,
    imgPath: "",
    behaviour: "Doesn’t make eye contact",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 228,
    imgPath: "",
    behaviour: "Loses skills he once had",
    description: "",
    atAge: 3,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 229,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_1.png"),
    behaviour: "Enjoys doing new things",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 230,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_2.png"),
    behaviour: "Plays “Mom” and “Dad”",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 231,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_3.png"),
    behaviour: "Is more and more creative with make-believe play",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 232,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_4.png"),
    behaviour: "Would rather play with other children than by himself",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 233,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_5.png"),
    behaviour: "Cooperates with other children",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 234,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_6.png"),
    behaviour: "Often can’t tell what’s real and what’s make-believe",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 235,
    imgPath: require("../../assets/img/Milestones/4YEARS/SOCIAL/4YEARS_SOCIAL_7.png"),
    behaviour: "Talks about what she likes and what she is interested in",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 236,
    imgPath: require("../../assets/img/Milestones/4YEARS/COMMUNICATION/4YEARS_COMMUNICATION_1.png"),
    behaviour:
      "Knows some basic rules of grammar, such as correctly using “he” and “she”",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 237,
    imgPath: require("../../assets/img/Milestones/4YEARS/COMMUNICATION/4YEARS_COMMUNICATION_2.png"),
    behaviour:
      "Sings a song or says a poem from memory such as the “Itsy Bitsy Spider” or the “Wheels on the Bus”",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 238,
    imgPath: require("../../assets/img/Milestones/4YEARS/COMMUNICATION/4YEARS_COMMUNICATION_3.png"),
    behaviour: "Tells stories",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 239,
    imgPath: require("../../assets/img/Milestones/4YEARS/COMMUNICATION/4YEARS_COMMUNICATION_4.png"),
    behaviour: "Can say first and last name",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 240,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_1.png"),
    behaviour: "Names some colors and some numbers",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 241,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_2.png"),
    behaviour: "Understands the idea of counting",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 242,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_3.png"),
    behaviour: "Starts to understand time",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 243,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_4.png"),
    behaviour: "Remembers parts of a story",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 244,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_5.png"),
    behaviour: "Understands the idea of “same” and “different”",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 245,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_6.png"),
    behaviour: "Draws a person with 2 to 4 body parts",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 246,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_7.png"),
    behaviour: "Uses scissors",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 247,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_8.png"),
    behaviour: "Starts to copy some capital letters",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 248,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_9.png"),
    behaviour: "Plays board or card games",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 249,
    imgPath: require("../../assets/img/Milestones/4YEARS/COGNITIVE/4YEARS_COGNITIVE_10.png"),
    behaviour: "Tells you what he thinks is going to happen next in a book",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 250,
    imgPath: require("../../assets/img/Milestones/4YEARS/PHYSICAL_DEVELOPMENT/4YEARS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Hops and stands on one foot up to 2 seconds",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 251,
    imgPath: require("../../assets/img/Milestones/4YEARS/PHYSICAL_DEVELOPMENT/4YEARS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Catches a bounced ball most of the time",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 252,
    imgPath: require("../../assets/img/Milestones/4YEARS/PHYSICAL_DEVELOPMENT/4YEARS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Pours, cuts with supervision, and mashes own food",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 253,
    imgPath: "",
    behaviour: "Can’t jump in place",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 254,
    imgPath: "",
    behaviour: "Has trouble scribbling",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 255,
    imgPath: "",
    behaviour: "Shows no interest in interactive games or make-believe",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 256,
    imgPath: "",
    behaviour:
      "Ignores other children or doesn’t respond to people outside the family",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 257,
    imgPath: "",
    behaviour: "Resists dressing, sleeping, and using the toilet",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 258,
    imgPath: "",
    behaviour: "Can’t retell a favorite story",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 259,
    imgPath: "",
    behaviour: "Doesn’t follow 3-part commands",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 260,
    imgPath: "",
    behaviour: "Doesn’t understand “same” and “different”",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 261,
    imgPath: "",
    behaviour: "Doesn’t use “me” and “you” correctly",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 262,
    imgPath: "",
    behaviour: "Speaks unclearly",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 263,
    imgPath: "",
    behaviour: "Loses skills he once had",
    description: "",
    atAge: 4,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 264,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_1.png"),
    behaviour: "Wants to please friends",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 265,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_2.png"),
    behaviour: "Wants to be like friends",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 266,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_3.png"),
    behaviour: "More likely to agree with rules",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 267,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_4.png"),
    behaviour: "Likes to sing, dance, and act",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 268,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_5.png"),
    behaviour: "Is aware of gender",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 269,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_6.png"),
    behaviour: "Can tell what’s real and what’s make-believe",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 270,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_7.png"),
    behaviour:
      "Shows more independence (for example, may visit a next-door neighbor by himself [adult supervision is still needed])",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 271,
    imgPath: require("../../assets/img/Milestones/5YEARS/SOCIAL/5YEARS_SOCIAL_8.png"),
    behaviour: "Is sometimes demanding and sometimes very cooperative",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "SOCIAL",
  },
  {
    id: 272,
    imgPath: require("../../assets/img/Milestones/5YEARS/COMMUNICATION/5YEARS_COMMUNICATION_1.png"),
    behaviour: "Speaks very clearly",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 273,
    imgPath: require("../../assets/img/Milestones/5YEARS/COMMUNICATION/5YEARS_COMMUNICATION_2.png"),
    behaviour: "Tells a simple story using full sentences",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 274,
    imgPath: require("../../assets/img/Milestones/5YEARS/COMMUNICATION/5YEARS_COMMUNICATION_3.png"),
    behaviour: "Uses future tense; for example, “Grandma will be here.”",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 275,
    imgPath: require("../../assets/img/Milestones/5YEARS/COMMUNICATION/5YEARS_COMMUNICATION_4.png"),
    behaviour: "Says name and address",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 276,
    imgPath: require("../../assets/img/Milestones/5YEARS/COGNITIVE/5YEARS_COGNITIVE_1.png"),
    behaviour: "Counts 10 or more things",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 277,
    imgPath: require("../../assets/img/Milestones/5YEARS/COGNITIVE/5YEARS_COGNITIVE_2.png"),
    behaviour: "Can draw a person with at least 6 body parts",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 278,
    imgPath: require("../../assets/img/Milestones/5YEARS/COGNITIVE/5YEARS_COGNITIVE_3.png"),
    behaviour: "Can print some letters or numbers",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 279,
    imgPath: require("../../assets/img/Milestones/5YEARS/COGNITIVE/5YEARS_COGNITIVE_4.png"),
    behaviour: "Copies a triangle and other geometric shapes",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 280,
    imgPath: require("../../assets/img/Milestones/5YEARS/COGNITIVE/5YEARS_COGNITIVE_5.png"),
    behaviour: "Knows about things used every day, like money and food",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "COGNITIVE",
  },
  {
    id: 281,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_1.png"),
    behaviour: "Stands on one foot for 10 seconds or longer",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 282,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_2.png"),
    behaviour: "Hops; may be able to skip",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 283,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_3.png"),
    behaviour: "Can do a somersault",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 284,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_4.png"),
    behaviour: "Uses a fork and spoon and sometimes a table knife",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 285,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_5.png"),
    behaviour: "Can use the toilet on her own",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 286,
    imgPath: require("../../assets/img/Milestones/5YEARS/PHYSICAL_DEVELOPMENT/5YEARS_PHYSICAL_DEVELOPMENT_6.png"),
    behaviour: "Swings and climbs",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 0,
    behavioursCategory: "PHYSICAL_DEVELOPMENT",
  },
  {
    id: 287,
    imgPath: "",
    behaviour: "Doesn’t show a wide range of emotions",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 288,
    imgPath: "",
    behaviour:
      "Shows extreme behavior (unusually fearful, aggressive, shy or sad)",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 289,
    imgPath: "",
    behaviour: "Unusually withdrawn and not active",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 290,
    imgPath: "",
    behaviour:
      "Is easily distracted, has trouble focusing on one activity for more than 5 minutes",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 291,
    imgPath: "",
    behaviour: "Doesn’t respond to people, or responds only superficially",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 292,
    imgPath: "",
    behaviour: "Can’t tell what’s real and what’s make-believe",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 293,
    imgPath: "",
    behaviour: "Doesn’t play a variety of games and activities",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 294,
    imgPath: "",
    behaviour: "Can’t give first and last name",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 295,
    imgPath: "",
    behaviour: "Doesn’t use plurals or past tense properly",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 296,
    imgPath: "",
    behaviour: "Doesn’t talk about daily activities or experiences",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 297,
    imgPath: "",
    behaviour: "Doesn’t draw pictures",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 298,
    imgPath: "",
    behaviour:
      "Can’t brush teeth, wash and dry hands, or get undressed without help",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
  {
    id: 299,
    imgPath: "",
    behaviour: "Loses skills he once had",
    description: "",
    atAge: 5,
    atAgeUnit: "YEARS",
    isActByDoctor: 1,
    behavioursCategory: "COMMUNICATION",
  },
];

const sampleImg =
  "../../assets/img/Milestones/2MONTHS/COGNITIVE/2MONTHS_COGNITIVE_2.png";

const findMilestoneImage = (id) => {
  const result = milestoneImages.find((obj) => {
    if (obj.id === id) {
      return obj;
    }
  });
  if (result.imgPath === "") {
    return sampleImg;
  }
  return result;
};

export default findMilestoneImage;
