export const CHILD_MILESTONE = [
    {
      title: 'at 5 Years',
      atAge: 60,
      atAgeTo: 1000,
      atAgeUnit: 'MONTHS',
      fetchAge: 5,
      fetchAgeUnit: 'YEARS',
    },
    {
      title: 'at 4 Years',
      atAge: 48,
      atAgeTo: 59,
      atAgeUnit: 'MONTHS',
      fetchAge: 4,
      fetchAgeUnit: 'YEARS',
    },
    {
      title: 'at 3 Years',
      atAge: 36,
      atAgeTo: 47,
      atAgeUnit: 'MONTHS',
      fetchAge: 3,
      fetchAgeUnit: 'YEARS',
    },
    {
      title: 'at 2 Years',
      atAge: 24,
      atAgeTo: 35,
      atAgeUnit: 'MONTHS',
      fetchAge: 2,
      fetchAgeUnit: 'YEARS',
    },
    {
      title: 'at 18 Months',
      atAge: 18,
      atAgeTo: 23,
      atAgeUnit: 'MONTHS',
      fetchAge: 18,
      fetchAgeUnit: 'MONTHS',
    },
    {
      title: 'at 1 Year',
      atAge: 12,
      atAgeTo: 17,
      atAgeUnit: 'MONTHS',
      fetchAge: 1,
      fetchAgeUnit: 'YEARS',
    },
    {
      title: 'at 9 Months',
      atAge: 9,
      atAgeTo: 11,
      atAgeUnit: 'MONTHS',
      fetchAge: 9,
      fetchAgeUnit: 'MONTHS',
    },
    {
      title: 'at 6 Months',
      atAge: 6,
      atAgeTo: 8,
      atAgeUnit: 'MONTHS',
      fetchAge: 6,
      fetchAgeUnit: 'MONTHS',
    },
    {
      title: 'at 4 Months',
      atAge: 4,
      atAgeTo: 5,
      atAgeUnit: 'MONTHS',
      fetchAge: 4,
      fetchAgeUnit: 'MONTHS',
    },
    {
      title: 'at 2 Months',
      atAge: 2,
      atAgeTo: 3,
      atAgeUnit: 'MONTHS',
      fetchAge: 2,
      fetchAgeUnit: 'MONTHS',
    },
  ];
  
  export const CHILD_MILESTONE_CATEGORY = {
    SOCIAL: 'SOCIAL',
    COMMUNICATION: 'COMMUNICATION',
    COGNITIVE: 'COGNITIVE',
    PHYSICAL_DEVELOPMENT: 'PHYSICAL_DEVELOPMENT',
    ACT_BY_DOCTOR: 'ACT_BY_DOCTOR',
  };
  