import { createAPIClient } from "./apiHandler";

const BASE_URL = process.env.REACT_APP_IMMUNIFY_API_URI;
const immunifyApiClient = createAPIClient(BASE_URL);

const ImmunifyApi = {
  getCountries: () => immunifyApiClient.doGet("/api/countries"),
  addParent: (data) => immunifyApiClient.doPost("/api/people", data),
  setFcmTokenFromWeb: (data) => immunifyApiClient.doPost("/api/webportal/setfcmtoken", data),
  webLogout: (data) => immunifyApiClient.doPost("/api/webportal/logout", data),
  updateParent: (data) => immunifyApiClient.doPatch("/api/people", data),
  addChild: (data) => immunifyApiClient.doPost("/api/children", data),
  getChildrenByParent: (data) => immunifyApiClient.doPost("/api/children/byParent", data),
  getChild: (data) => immunifyApiClient.doPost("/api/children/single", data),
  updateChild: (data) => immunifyApiClient.doPatch("/api/children", data),
  searchParent: (data) => immunifyApiClient.doPost("/api/people/multiple", data),
  activateCard: (data) => immunifyApiClient.doPost("/api/children/card", data),
  getChildByQrCode: (data) => immunifyApiClient.doPost("/api/children/qrCode", data),
  vaccinateChild: (data) => immunifyApiClient.doPatch("/api/vaccinations", data),
  getVaccineTradeNames: () => immunifyApiClient.doGet("/api/vaccines/tradeNames"),
  getVaccines: () => immunifyApiClient.doGet("/api/vaccines/multiple"),
  getVaccinesByTradeName: (data) => immunifyApiClient.doPost("/api/vaccines/searchable/tradeNames", data),
  addVaccine: (data) => immunifyApiClient.doPost("/api/vaccines/requests/schedules", data),
  addGrowthInfo: (data) => immunifyApiClient.doPost("/api/children/growthInfo", data),
  getGrowathInfo: ({ childId }) => immunifyApiClient.doGet(`/api/children/growthInfo/${childId}`),
  orderDevices: (data) => immunifyApiClient.doPost("/api/order", data),
  requestVaccines: (data) => immunifyApiClient.doPost("/api/vaccines/request", data),
  getVaccineViseReport: (data) => immunifyApiClient.doPost("/api/vaccineWise", data),
  getTotalVaccinatedReport: (data) => immunifyApiClient.doPost("/api/totalVaccinated", data),
  getTotalOverdueReport: (data) => immunifyApiClient.doPost("/api/childOverDue", data),
  getOverdueAllReport: (data) => immunifyApiClient.doPost("/api/reports/due/vaccines/lists", data),
  getChildVaccinatedDetailsByVaccine: (data) => immunifyApiClient.doPost("/api/totalChildVaccinatedDetails", data),
  getChildVaccinationOverdueDetailsByVaccine: (data) => immunifyApiClient.doPost("/api/childOverdueDetails", data),
  getLoggedInUser: (data) => immunifyApiClient.doPost("/api/getUserDetails/v2", { ...data, isAdmin: true }),
  getVaccinatedCountWeekly: (data) => immunifyApiClient.doPost("/api/vaccinatedCountWeekly", data),
  getNotVaccinatedCountWeekly: (data) => immunifyApiClient.doPost("/api/notVaccinatedCountWeekly", data),
  getVaccinatedCountMonthly: (data) => immunifyApiClient.doPost("/api/vaccinatedCountMonthly", data),
  getVaccinationForcast: (data) => immunifyApiClient.doPost("/api/vaccinationForecast", data),
  addNewUserEvent: (data) => immunifyApiClient.doPost("/api/addNewUserEvent", data),
  updateNewEvent: (data) => immunifyApiClient.doPost("/api/updateUserEvent", data),
  getScheduleEvents: (data) => immunifyApiClient.doPost("/api/getScheduleEvent", data),
  getUserEvents: (data) => immunifyApiClient.doPost("/api/events", data),
  getVaccinationByCityWeekly: (data) => immunifyApiClient.doPost("/api/vaccinationCityWiseWeekly", data),
  getTotalVaccinatedCount: (data) => immunifyApiClient.doPost("/api/totalVaccinatedCount", data),
  getIssuedQrCodeCount: (data) => immunifyApiClient.doPost("/api/issuedQrCodeCount", data),
  getNewBornChildCount: (data) => immunifyApiClient.doPost("/api/newBornChildCount", data),
  getTradenames: () => immunifyApiClient.doGet("/api/tradenames/default"),
  deleteTradenames: (data) => immunifyApiClient.doDelete("/api/tradenames", data),
  getPendingTradenames: () => immunifyApiClient.doGet("/api/tradenames/nonapproval"),
  getSearchableVaccine: (data) => immunifyApiClient.doPost("/api/vaccines/searchable/vaccineNames", data),
  getManufacturers: () => immunifyApiClient.doGet("/api/manufacturers/all"),
  addTradenames: (data) => immunifyApiClient.doPost("/api/tradenames", data),
  approveTradenames: (data) => immunifyApiClient.doPatch("/api/tradenames/status", data),

  // Admin App Routes
  getVacCities: () => immunifyApiClient.doGet("/api/vacCities"),
  getVacStates: () => immunifyApiClient.doGet("/api/vacStates"),
  getVacTypes: () => immunifyApiClient.doGet("/api/vacTypes"),
  getVacNames: () => immunifyApiClient.doGet("/api/vacsNames"),
  getVacCenters: (data) => immunifyApiClient.doPost("/api/vacs/multiple", data),
  createVacCenter: (data) => immunifyApiClient.doPost("/api/vacs", data),
  updateVacCenter: (data) => immunifyApiClient.doPatch("/api/UpdateVacs", data),
  createVacSchedule: (data) => immunifyApiClient.doPost("/api/vacSchedules", data),
  updateVacSchedule: (data) => immunifyApiClient.doPatch("/api/vacSchedules", data),
  deleteVacSchedule: (data) => immunifyApiClient.doPatch("/api/deleteVacSchedules", data),
  getVacSchedules: (data) => immunifyApiClient.doPost("/api/vacSchedules/multiple", data),
  addVaccineToSchedule: (data) => immunifyApiClient.doPost("/api/vacSchedules/detail", data),
  getScheduleDetails: (data) => immunifyApiClient.doPost("/api/vacSchedules/selectedScheduleDetails", data),
  getCenterArtworkDetails: (data) => immunifyApiClient.doPost("/api/getCenterArtworkDetails", data),
  uploadArtwork: (data) => immunifyApiClient.doPost("/api/uploadArtwork", data, false),
  addArtwork: (data) => immunifyApiClient.doPost("/api/addArtwork", data),
  updateArtwork: (data) => immunifyApiClient.doPost("/api/updateArtworkDetails", data),
  getArtworks: (data) => immunifyApiClient.doPost("/api/artworks", data),
  generateQrCodes: (data) => immunifyApiClient.doPost("/api/qrCodes", data),
  getQrCodes: (data) => immunifyApiClient.doPost("/api/qrCodes/vacs", data),
  printCards: (data) => immunifyApiClient.doPost("/api/qrCodes/print", data),
  getSignedUrs: (data) => immunifyApiClient.doPost("/api/sign", data),
  addNewVaccine: (data) => immunifyApiClient.doPost("/api/vaccines", data),
  updateVaccine: (data) => immunifyApiClient.doPatch("/api/vaccines", data),
  addNewTradename: (data) => immunifyApiClient.doPost("/api/vaccines/tradeNames", data),
  getPrintedBatches: (data) => immunifyApiClient.doPost("/api/qrCodes/printed-batches", data),
  getconsultationTimes: (data) => immunifyApiClient.doPost("/api/doctona/consultations/all", data),
  getSentEmails: (data) => immunifyApiClient.doPost("/api/get/sent-notification-email", data),
  getSentNotifications: (data) => immunifyApiClient.doPost("/api/get/sent-notification-email", data),
  getDraftNotifications: (data) => immunifyApiClient.doPost("/api/get/draft-notification-email", data),
  getDraftEmails: (data) => immunifyApiClient.doPost("/api/get/draft-notification-email", data),
  addAdmin: (data) => immunifyApiClient.doPost("/api/admin-users", data),
  updateAdmin: (data) => immunifyApiClient.doPatch("/api/admin-users", data),
  getAdminAddedUsers: (data) => immunifyApiClient.doPost("/api/get-users-by-creator", data),
  // Doctor App Routes
  getMyChildPatients: (id) => immunifyApiClient.doGet(`/api/doctor/childrenPatientList?addedBy=${id}`),
  getMyAdultPatients: (id) => immunifyApiClient.doGet(`/api/doctor/parentPatientList?addedBy=${id}`),
  getNonApprovedUsers: () => immunifyApiClient.doGet("/api/nonapproval/users"),
  approveDoctor: (data) => immunifyApiClient.doPatch("/api/approval/users", data),
  removeDoctor: (data) => immunifyApiClient.doPost("/api/doctona/delete", data),
  initVideoCall: (data) => immunifyApiClient.doPost("/api/doctona/doctors/call", data),
  getDoctorProfileInfo: (data) => immunifyApiClient.doPost("/api/doctona/doctors/profile", data),
  getDoctorProfilePicture: (id) => immunifyApiClient.doGet("/api/doctona/doctors/profile/profilepicture/" + id),
  getDoctorSpecializations: () => immunifyApiClient.doGet("/api/doctona/specializations"),
  updateDoctorProfileData: (data) => immunifyApiClient.doPatch("/api/doctona/doctors/profile", data),
  addDoctorEducationInfo: (data) => immunifyApiClient.doPost("/api/doctona/doctors/education", data),
  deleteDoctorEducationInfo: (data) => immunifyApiClient.doDelete(`/api/doctona/doctors/education?educationEntryId=${data}`),
  getDoctorWorkExpInfo: (data) => immunifyApiClient.doGet("/api/doctona/doctors/experience/" + data),
  addDoctorWorkExpInfo: (data) => immunifyApiClient.doPost("/api/doctona/doctors/experience", data),
  deleteConsultationPlan: ({ id, appoinmentType, personId }) => immunifyApiClient.doDelete(`/api/doctona/doctors/consulations/delete?id=${id}&appoinmentType=${appoinmentType}&personId=${personId}`),
  deleteDoctorWorkExpInfo: (data) => immunifyApiClient.doDelete(`/api/doctona/doctors/experience?workExpEntryId=${data}`),
  addDoctorSession: (data) => immunifyApiClient.doPost("/api/doctona/doctors/session", data),
  deleteDoctorSession: (data) => immunifyApiClient.doPatch("/api/doctona/doctors/session", data),
  addDoctorHospital: (data) => immunifyApiClient.doPost("/api/doctona/doctors/hospital", data),
  addDoctor: (data) => immunifyApiClient.doPost("/api/doctona/doctors", data),
  updateDoctorEducation: (data) => immunifyApiClient.doPost("/api/doctona/doctors/education", data),
  updateDoctorDescription: (data) => immunifyApiClient.doPatch("/api/doctona/doctors/description", data),
  getDoctorEducation: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/education/${immId}`),
  getDoctorDescription: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/description?doctorId=${immId}`),
  updateDoctorWorkExperience: (data) => immunifyApiClient.doPost("/api/doctona/doctors/experience", data),
  getDoctorWorkExperience: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/experience/${immId}`),
  updateDoctorHospital: (data) => immunifyApiClient.doPost("/api/doctona/doctors/hospital", data),
  getDoctorHospital: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/hospital/${immId}`),
  updateDoctorBackAccount: (data) => immunifyApiClient.doPost("/api/doctona/doctors/bankaccount", data),
  getDoctorBankAccount: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/bankaccount/${immId}`),
  addConsultationPlan: (data) => immunifyApiClient.doPost("/api/doctona/doctors/consulations", data),
  getConsultationPlans: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/consulations?personId=${immId}`),
  updateDoctorSession: (data) => immunifyApiClient.doPatch("/api/doctona/doctors/session", data),
  getDoctorSessions: ({ immId }) => immunifyApiClient.doGet(`/api/doctona/doctors/session?doctorId=${immId}`),
  getAppointmentTypes: () => immunifyApiClient.doGet("/api/doctona/appointment-types"),
  getSpecializations: () => immunifyApiClient.doGet("/api/doctona/specializations"),
  searchDoctors: (data) => immunifyApiClient.doPost("/api/search/doctors", data),
  uploadDoctorProfilePicture: (data) => immunifyApiClient.doPost("/api/doctona/doctors/upload", data, false),
  getSignedProfileUrl: (data) => immunifyApiClient.doPost("/api/doctona/doctors/sign", data),
  getMyPatients: (data) => immunifyApiClient.doGet(`/api/doctona/doctor/patients/v2?personId=${data}`),
  getPatientAllData: (data) => immunifyApiClient.doPost("/api/doctona/users/info/all", data),
  getPatientLatestGrowthInfo: (data) => immunifyApiClient.doPost("/api/children/latestGrowthById", data),
  addPrescription: (data) => immunifyApiClient.doPost("/api/doctona/healthFiles/upload/v2", data),
  scheduleAppointment: (data) => immunifyApiClient.doPost("/api/communicator/appointments/schedule", data),
  getDoctorBankAccount: (data) => immunifyApiClient.doGet(`/api/doctona/doctors/bankaccount/${data}`),
  addDoctorBankAccount: (data) => immunifyApiClient.doPost("/api/doctona/doctors/bankaccount", data),
  getDoctorEvents: (data) => immunifyApiClient.doGet(`/api/doctona/doctor/events/${data}`),
  updateDoctorEvent: (data) => immunifyApiClient.doPost("/api/doctor/updateEvents", data),
  addDoctorEvent: (data) => immunifyApiClient.doPost("/api/doctona/doctor/events/create", data),
  deleteDoctorEvent: (data) => immunifyApiClient.doPost("/api/doctor/deleteEvents", data),
  getDoctorAppointments: ({ immId, date }) => immunifyApiClient.doGet(`/api/doctona/doctors/appoinments?immId=${immId}&date=${date}`),
  cancelAppointment: (data) => immunifyApiClient.doPost("/api/doctona/doctor/appointments/cancel", data),
  getVacVialPresigndUrl: (data) => immunifyApiClient.doGet(`/api/vaccines/vial/getpresignedurl?key=${data}`),

  //Parent Endpoints
  addChildByParent: (data) => immunifyApiClient.doPost("/api/children", data),
  getParentAppointmentData: (data) => immunifyApiClient.doPost("/api/doctona/users/appointmentInfo", data),
  cancelAppointmentByParent: (data) => immunifyApiClient.doPost("/api/doctona/users/appointments/cancel", data),
  getMyChildren: (data) => immunifyApiClient.doPost("/api/children/byMobileParent", data),
  getMyChildrenQRCodes: (data) => immunifyApiClient.doGet(`/api/children/qrCodes/${data}`),
  editChildDetails: (data) => immunifyApiClient.doPatch("/api/childGeneralInfo", data),
  getChildLabReports: (data) => immunifyApiClient.doGet(`/api/doctona/child/healthfiles/${data}`),
  emailChildHealthFile: (data) => immunifyApiClient.doPost("/api/doctona/child/healthfile/sendemail", data),
  deleteChildLabReport: (data) => immunifyApiClient.doPost("/api/doctona/child/deletelabreport/byparent", data),
  deleteChildPrescription: (data) => immunifyApiClient.doPost("/api/doctona/child/deleteprescription/byparent", data),
  addChildHealthFile: (data) => immunifyApiClient.doPost("/api/doctona/healthFiles/upload/v2", data),
  getChildPrescriptions: ({ immId, userType }) => immunifyApiClient.doGet(`/api/doctona/users/prescription?immId=${immId}&userType=${userType}`),
  getSingleChildInfo: (data) => immunifyApiClient.doPost("/api/child/byMobileParent", data),
  getChildVacSchedulePercentage: (data) => immunifyApiClient.doGet(`/api/vaccination/percentage/${data}`),
  getQrDate: (data) => immunifyApiClient.doPost("/api/children/subscription/get-qrCode", data),
  manageVaccinationByParent: (data) => immunifyApiClient.doPatch("/api/vaccinations/byParent", data),
  getChildVacScheduleLinkByParent: (data) => immunifyApiClient.doPost("/api/vacschedule/downloadpdf", data),
  emailChildVacScheduleLinkByParent: (data) => immunifyApiClient.doPost("/api/vacschedule/sendmail", data),
  getSelectedChildGrowthInfo: (childId) => immunifyApiClient.doGet(`/api/children/growthInfo/${childId}`),
  getChildNutritionPlan: (data) => immunifyApiClient.doPost("/api/nutrition", data),
  getChildMilestoneImages: (data) => immunifyApiClient.doPost("/api/getMilestoneImages", data),
  getChildMilestonePercentage: (childId) => immunifyApiClient.doGet(`/api/milestone/percentage/${childId}`),
  getSelectedChildMilestones: (data) => immunifyApiClient.doPost("/api/milestoneList", data),
  updateChildMilestones: (data) => immunifyApiClient.doPost("/api/addChildMilestone", data),
  getParentProfilePictureById: (pid) => immunifyApiClient.doGet(`/api/doctona/parent/profile/profilepicture/${pid}`),
  getBasicParentData: (data) => immunifyApiClient.doPost("/api/people/single", data),
  getParentAdditionalData: (pid) => immunifyApiClient.doGet(`/api/doctona/users/basic/${pid}`),
  updateParentProfileBasicData: (data) => immunifyApiClient.doPatch("/api/doctona/users/update/profiledetails", data),
  updateParentProfileAdditionalData: (data) => immunifyApiClient.doPatch("/api/doctona/users/updateorcreate/parentprofilebasictab", data),
  getSymptomsList: () => immunifyApiClient.doGet("/api/doctona/symptoms"),
  searchDoctors: (data) => immunifyApiClient.doPost("/api/doctona/doctors/results", data),
  getDoctorAppointmentTypes: (data) => immunifyApiClient.doPost("/api/doctona/appointments/appointmentTypes", data),
  getSelectedAppointmentTypeDates: (data) => immunifyApiClient.doPost("/api/doctona/appointments/dates", data),
  getSelectedAppointmentTypeTimes: (data) => immunifyApiClient.doPost("/api/doctona/appointments/times", data),
  validateCoupon: (data) => immunifyApiClient.doPost("/api/doctona/users/coupons", data),
  captureAppointment: (data) => immunifyApiClient.doPost("/api/doctona/appointments", data),
  createAppointment: (data) => immunifyApiClient.doPost("/api/doctona/appointments/payments", data),
  downloadAppointmentPaymentSummary: (data) => immunifyApiClient.doPost("/api/doctona/users/payment/summary/download", data),
  emailAppointmentPaymentSummary: (data) => immunifyApiClient.doPost("/api/doctona/users/payment/summary/email", data),
  deleteChildGrowthInfo: ({ childId, id, height, weight, hcw }) => immunifyApiClient.doDelete(`/api/children/growthInfo?childId=${childId}&id=${id}&height=${height}&weight=${weight}&hcw=${hcw}`),
  completeSpecificAppointment: (data) => immunifyApiClient.doPost("/api/doctona/doctor/slots/complete", data),
};

export default ImmunifyApi;
